# Assignment 8: Neural Networks

Only use the already imported library `numpy` and the Python standard library. For the evaluation you may also use scikit-learn (`sklearn`) and `matplotlib`. Make sure that the dataset `airfoil_self_noise.csv` is in the same directory as the notebook.

List your team members (name and immatriculation number) and indicate whether you are a B.Sc. Data Science or other group in the following cell:

In [150]:
import numpy as np

def load_dataset(path):
    from sklearn.model_selection import train_test_split
    
    data = np.genfromtxt(path)
    X, y = data[:, :5], data[:, 5]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2020)

    return X_train, X_test, y_train, y_test
    

X_train, X_test, y_train, y_test = load_dataset('airfoil_self_noise.csv')

- Kuang-Yu Li, st169971@stud.uni-stuttgart.de, 3440829 
- Ya-Jen Hsu, st169013@stud.uni-stuttgart.de, 3449448 
- Gabriella Ilena, st169935@stud.uni-stuttgart.de, 3440942

## Task 3: Feedforward Neural Network: Programming

In this task, you will implement a feedforward neural network for regression. The hyperparameters of the model are:
- `input_dim`: The dimension of the input vector.
- `output_dim`: The dimension of the output vector.
- `width`: The dimension of each hidden layer.
- `depth`: The number of hidden layers. For B.Sc. Data Science students, this parameter is constant with a value of 1.
- `learning_rate`: The learning rate for gradient descent.
- `epochs`: The number of epochs/iterations performed during training.

B.Sc. Data Science only have to implement for a single hidden layer, i.e. `depth = 1`. All other students have to implement the network for any `depth >= 1`.

The activation function for each hidden layer is ReLU (g(x) = max(0, x)). The output layer uses the identity as activation, since our objective is regression.

You have to implement the `FeedforwardNeuralNetworkRegressor`.

The `__init__` method initializes the network.
Initialize each weight and bias randomly with a standard Gaussian distribution using the numpy function `numpy.random.normal` with default parameters.

The `fit` method trains the network.
Use backpropagation with gradient descent similar to Task 2.
Use the whole training data set for each training epoch.
Use the mean squared error as loss function.

The `predict` method computes the forward-pass of the network.

Evaluate your classifier on the test data with the mean squared error and compare your results to your linear regression model from assignment 3. Try out different hyper-parameters and compare the results. You may want to normalize your input and output data for better performance.

In [151]:
class FeedforwardNeuralNetworkClassifier(object):
    def __init__(self, input_dim, output_dim, width, depth, learning_rate, epochs):
        # Add your code, such as initialization of weights here.
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.width = width
        self.depth = depth
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.w_in = np.random.randn(width, input_dim)
        self.b_in = np.random.randn(width, 1)
        self.w_hidden = np.random.randn(width, width, depth)
        self.b_hidden = np.random.randn(width, 1, depth)
        self.w_out = np.random.randn(output_dim, width)
        self.b_out = np.random.randn(output_dim, 1)
        print("======INITIAL PARAMETERS======")
        print("input_dim: ", input_dim)
        print("output_dim: ", output_dim)
        print("width: ", width)
        print("depth: ", depth)
        print("learning_rate: ", learning_rate)
        print("epochs: ", epochs)
        print(self.w_in)
        pass
        
    def fit(self, X, y):
        
        # Implement your training here.
        pass
    
    def predict(self, X):
        # Implement your prediction here.
        print("[predict]X shape:",X.shape)
        Z = np.zeros((width, X.shape[0]), dtype=float)
        print("[predict]Z shape:",Z.shape)
        for i in range (2):
        #for i in range (X.shape[0]):
            x = X[i, :]
            print("[predict] x: ",x)
            x_re = x.reshape(X.shape[1], 1)
            print("[predict] x: ",x_re)
            print("[predict] w_in:\n ", self.w_in)
            print("[predict] b_in:\n", self.b_in)
            z = self.w_in.dot(x_re) + self.b_in
            # Z[:, i] = z;
            a = self.relu(z)
            print("[predict] z:\n ", z)
            print("[predict] a:\n ", a)
            for j in range(1):
            #for j in range(depth):
                z = self.w_hidden[:,:,j].dot(a) + self.b_hidden[:,:, j]
                a = self.relu(z)
        
        y_hat = np.zeros((self.output_dim, 1), dtype=float)
        return y_hat
    
    def relu(self, Z):
        return np.maximum(0,Z)


In [152]:
# Implement your training and evaluation here.
print("input shape:", X_train.shape)
print("output shape:", y_train.shape)
input_dim = X_train.shape[1]
output_dim = 1
width = 3
depth = 1
learning_rate = 0.01
epochs = 1
myFNNC = FeedforwardNeuralNetworkClassifier(input_dim, output_dim, width, depth, learning_rate, epochs)

myFNNC.predict(X_test)

def test():
    print(X_train[1, :])
    x = X_train[1, :]
    print(x.reshape(5,1))
    one = np.ones(5,dtype=float)
    print(one)
    one_15 = np.ones((1,5),dtype=float)
    print(one_15)
    one_reshape = one.reshape(5,1)
    print(one_reshape)
    pass

input shape: (1052, 5)
output shape: (1052,)
======INITIAL PARAMETERS======
input_dim:  5
output_dim:  1
width:  3
depth:  1
learning_rate:  0.01
epochs:  1
[[ 0.94723014  0.52098942  0.01155004  0.29971977 -1.1009922 ]
 [ 1.51003057 -0.35246377 -1.15851723  0.08009012 -0.29316302]
 [-0.87053258  0.45659711  2.10333383  0.5735362  -0.04332555]]
[predict]X shape: (451, 5)
[predict]Z shape: (3, 451)
[predict] x:  [5.00000e+03 3.30000e+00 1.01600e-01 7.13000e+01 2.02822e-03]
[predict] x:  [[5.00000e+03]
 [3.30000e+00]
 [1.01600e-01]
 [7.13000e+01]
 [2.02822e-03]]
[predict] w_in:
  [[ 0.94723014  0.52098942  0.01155004  0.29971977 -1.1009922 ]
 [ 1.51003057 -0.35246377 -1.15851723  0.08009012 -0.29316302]
 [-0.87053258  0.45659711  2.10333383  0.5735362  -0.04332555]]
[predict] b_in:
 [[ 1.15658253]
 [-0.64839029]
 [ 0.17370635]]
[predict] z:
  [[ 4760.39552475]
 [ 7553.93343598]
 [-4309.87567799]]
[predict] a:
  [[4760.39552475]
 [7553.93343598]
 [   0.        ]]
[predict] x:  [1.00000e+0